### ISSUE TITLE
Al perder no funciona el continuar

### ISSUE THREAD

**Issue by Okami115** [Chesog/Asteroids#3]
Luego de perder, solo funciona el botón de reinicio, pero al reiniciar, el juego, se pone en pausa y ahí se puede utilizar el botón de continuar.

**Comment by Chesog** [comment]
El echo de que al reiniciar este puesta la pausa esta echa a propósito de esa manera ,  la idea es que al perder tengas que reiniciar en caso de querer volver a jugar pero se tiene en cuenta para el futuro 👍
